# Use root/example as user/password credentials
version: '3.2'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - "sqlcredentials.env"
    ports:
      - "1433:1433"