# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=123
      - MARIADB_DATABASE=semfilas
      - MARIADB_USER=semfilas
      - MARIADB_PASSWORD=123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local